services:
  backend:
    build:
      context: ./Webapp/app/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Webapp/app/backend:/app

  frontend:
    build:
      context: ./Webapp/app/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
